### ISSUE TITLE
slowdown script not generating results

### ISSUE THREAD

**Issue by mustansarsaeed** [PlatformLab/homa-paper-artifact#2]
Hi,

I have reserved full chassis and conducted the experiment but after slowdown generation and running script, it exit with following error"

```
Warning: Ignoring unknown aesthetics: width
Warning: Ignoring unknown aesthetics: width
null device 
          1 
Warning: Ignoring unknown aesthetics: width
Error in pdf(sprintf("impl/slowdownImpl_%s_rho%s_tail.pdf", workload,  : 
  cannot open file 'impl/slowdownImpl_W3_rho48_tail.pdf'
Execution halted

```

And generated pdf is also not right plotted. Please see the attached file.
[slowdownImpl.pdf](https://github.com/PlatformLab/homa-paper-artifact/files/2987877/slowdownImpl.pdf)

As slowdown.txt generted by runworkload script has numbers for Basic, Homap1, homap2, homap4, homap8 then graph should display all configurations of homa but it only displays Basic? Paper also have curves for Inf-RC, TC-MC etc. Please share the sctipt updates.

**Comment by yilongli** [comment]
Can you show me the raw slowdown numbers? 

InfRC and TCP-MC plots are less interesting. Besides, InfRC only works on our internal RAMCloud cluster at Stanford. Therefore, I don't currently have plan to reproduce them.

**Comment by mustansarsaeed** [comment]
Please see the attached raw slowdown numbers for W3 workload
[slowdownImpl.txt](https://github.com/PlatformLab/homa-paper-artifact/files/2989831/slowdownImpl.txt)

**Comment by yilongli** [comment]
I have pushed a new commit that includes the original experiment data (including TCP and InfRC) and the R script to plot them. Unfortunately, I wasn't able to fix the R script to work with the new data. I will ping the first author to help me take a look. This might take a while though. Or you are welcome to try if you know R.

**Comment by mustansarsaeed** [comment]
@yilongli Thanks for updating the repository. This slowdownImpl.txt file should be same if I do experiment on cluster and runworkloads to generate slowdown numbers. Is this right? Is there any additional settings for the original experiment data? Just confirming.

**Comment by yilongli** [comment]
No, `old-experiment-data/slowdownImpl.txt` was the original data experiment. This repo is developed later for the artifact evaluation and the current `run_workload.sh` will result in a slightly different `slowdownImpl.txt` file (e.g., their first columns are different).

**Comment by mustansarsaeed** [comment]
If I have to do some experimentation with HomaTransport and then generate slowdown numbers then how can I do that ? Because the slowdown numbers generated by artifact are different? How can the results be reproduced, just thinking in terms of that.

**Comment by yilongli** [comment]
You can generate latest slowdown numbers following the instructions of this repo. The slowdown numbers are not that different from the old experiment data. In fact, I believe the current numbers are slightly better. I am just saying the first columns of the two files are slightly different and the out-dated R script `slowdownImpl.r` has trouble plotting the new data properly somehow.

**Comment by mustansarsaeed** [comment]
Ok. Got it. With the old data and script, graphs are being generated fine. I'll do the experimentation on cluster and will try to fix the script, and will get back to you in case of any stuck point.

**Comment by mustansarsaeed** [comment]
Hi @yilongli 
I have generated slowdown numbers for workload W3 and W4, I am attaching generated `slowdown W4` for reference 
[slowdownImpl.txt](https://github.com/PlatformLab/homa-paper-artifact/files/3003789/slowdownImpl.txt), 

I am comparing my W4 numbers with the numbers you provided. There are multiple issues which I can see:

Your generated numbers and my numbers are completely different. Please see the attached images:
**My Numbers:** 
![my_w4_numbers](https://user-images.githubusercontent.com/7519716/54940305-4d082900-4f4c-11e9-9b36-d1ba6e48e22c.png)

**Oringal W4 numbers:** 
![original_w4_numbers](https://user-images.githubusercontent.com/7519716/54940318-54c7cd80-4f4c-11e9-9aaf-8b61bf6d773a.png)

**Secondly,**
I am seeing the transport types, it has different labels than mine. Like HomaP107, HomaP204, HomaP8O3 76 w4 etc. What are these referring to? As, script is unable to parse my generate file, when I give yours, it start producing result? I am also attaching my slowdown numbers can you please verify. 
[slowdownImpl.txt](https://github.com/PlatformLab/homa-paper-artifact/files/3003832/slowdownImpl.txt) and it would be nice if you can comment over different numbers, labels and script.

**Comment by mustansarsaeed** [comment]
@yilongli Any pointer would be appreciated.

**Comment by yilongli** [comment]
Have you compared your slowdown numbers with https://github.com/PlatformLab/homa-paper-artifact/blob/master/experiment-data/W4/slowdownImpl.txt? Have you also compared the absolute numbers with, say, https://github.com/PlatformLab/homa-paper-artifact/blob/master/experiment-data/W4/HomaP8_W4_76_experiment.txt?

`HomaPxOy` means Homa is allowed to use `x` priorities and the degree of overcommitment is `y`. These concepts are explained in the paper. Also, take a look at the `run_workload.sh` script and https://github.com/PlatformLab/RAMCloud/blob/master/config/transport.txt. They should help you understand how these parameters are passed to HomaTransport.

**Comment by mustansarsaeed** [comment]
Thank you @yilongli  for your support. I have compared the my absolute numbers HomaP8_W4_76_experiment.txt  with https://github.com/PlatformLab/homa-paper-artifact/blob/master/experiment-data/W4/HomaP8_W4_76_experiment.txt , they are quit different. My numbers are much larger. Please see my attached numbers:
[HomaP8_W4_76_experiment.txt](https://github.com/PlatformLab/homa-paper-artifact/files/3023864/HomaP8_W4_76_experiment.txt) . Secondly, `config/transport` is showing  overcommit value `homa+dpdk:rttMicros=8,numPrio=8,unschedPrio=1,degreeOC=7` and `runworkload.sh` should output HomaP107, HomaP207, HomaP407 etc in `slowdownImpl.txt` but why it does only `echo`  HomaP1, HomaP2 etc. I did tweak the slowdown script which is expecting the overcommitted labels as `HomaPx0y`, removed this and set `HomaPx`. It produced the attached result:
[slowdownImpl_W4_rho76_tail.pdf](https://github.com/PlatformLab/homa-paper-artifact/files/3023884/slowdownImpl_W4_rho76_tail.pdf). Can you please help in this? I ran the experiment as `benchmarks/homa/scripts/run_workload.sh W4 16 1800`, ran W4 for 30 minutes for every configuration.

**Comment by yilongli** [comment]
Can you run `i7z` on one of the `rcXX` nodes to check the frequencies and C-state information of each core? Ideally, all cores should not enter C-states deeper than C1 for the purpose of running this benchmark.

Next, can you do `sudo cat /proc/cmdline` to check if the kernel boot parameters contain ` intel_idle.max_cstate=0 idle=poll`? Also, do `sudo cpupower frequency-info -g` to check if the CPU governor is `performance`. If not, you would have to do `sudo cpupower frequency-set -g performance` on all of the `rcXX` nodes (e.g., one way would be to use `pdsh` to issue the command on `rcmaster`).

`HomaPxOy` is the old notation we used in the graph. However, it turns out to be a bit messy and we decide to switch to the `HomaPx` notation and have only one plot (i.e., one fixed degree of over-commitment) per `numPrio`. The shape of the plot in the graph you produced seems about right. Once you fixed the 99% slowdown numbers, it should be good.

**Comment by mustansarsaeed** [comment]
Thank you @yilongli  for responding. I run `i7z` command and output is 
![i7z_command](https://user-images.githubusercontent.com/7519716/55271252-808be000-52cb-11e9-8a74-40bdcae03068.png). Secondly, `intel_idle.max_cstate=0 idle=poll` is present on all nodes in `/proc/cmdline`. `performance` was not set on all nodes therefore i run command using `pdsh` on `rcmaster`. After doing all this, I again ran the experiment `W4` for 10 minutes. Again the result is 
[slowdownImpl_W4_rho76_tail.pdf](https://github.com/PlatformLab/homa-paper-artifact/files/3025125/slowdownImpl_W4_rho76_tail.pdf). Can you please help what is the missing part? Or I should consider this graph as correct ? But this does not match with the paper as `HomaP4` and `HomaP8` starts from higher numbers. Although plots convergence is almost same as the original plots but just concerning about `HomaP4` and `HomaP8`.

**Comment by yilongli** [comment]
I need to see the raw numbers. Is there any improvement after setting the performance governor? Can you run `i7z` again on one of the `rcXX` node?

**Comment by mustansarsaeed** [comment]
I don't see any improvement. In my understanding, I can see my numbers are greater than the original that's why `HomaP4` and `HomaP8` starts from bigger number. latest slowdown numbers 
[slowdownImpl.txt](https://github.com/PlatformLab/homa-paper-artifact/files/3025157/slowdownImpl.txt) and absolute `HomaP8` numbers are 
[HomaP8_W4_76_experiment.txt](https://github.com/PlatformLab/homa-paper-artifact/files/3025158/HomaP8_W4_76_experiment.txt). I have run again `i7z` on `rc40`
![i7z_command_latest](https://user-images.githubusercontent.com/7519716/55271627-b03de680-52d1-11e9-9ea3-b70eeda44f43.png) and I am using the original script you shared in experimental data. Just changed `HomaPx0y`  to `HomaPx`.

Am I missing something?

**Comment by yilongli** [comment]
Hmm, this is weird. Usually, disabling deep C-states and using performance CPU governor should fix the 99%-tile tail latency. Are you sure the output of `i7z` of other nodes are the same as the `rc40`? Can you also run the experiment using, say, 32 nodes? This should help you collect more data points.

You might also want to run `turbostat --debug sleep 10` to monitor service management interrupts (SMI), which can also cause unexpected jitters. I think you should see only 8 SMIs per second if the system is properly tuned.

**Comment by yilongli** [comment]
One more thing you can try is to clone [this repo](https://github.com/yilongli/OSJitterTest), compile, and run the `user_loop` program on one of the `rcXX` node to monitor unexpected jitters.

**Comment by mustansarsaeed** [comment]
Hi @yilongli , I am using `chassis 12`. Here are few observations:
1. `rcnfs` node is showing `16` cores, rest are `7` cores
2. `1` node is showing following error while executing `sudo cpupower frequency-set -g performance`
 

```
Setting cpu: 0
Setting cpu: 1
Setting cpu: 2
Setting cpu: 3
Setting cpu: 4
Setting cpu: 5
Error setting new values. Common errors:
- Do you have proper administration rights? (super-user?)
- Is the governor you requested available and modprobed?
- Trying to set an invalid policy?
- Trying to set a specific frequency, but userspace governor is not available,
   for example because of hardware which cannot be set to a specific frequency
   or because the userspace governor isn't loaded?
```
Can these be the issues? I have not yet executed `user_loop` as I have errors on one node while settign governor to` performance`.

**Comment by yilongli** [comment]
These are unlikely to be the problems. `rcnfs` is not used to run the experiment. `rcXX` should have 8 or 16 cores (depending on whether SMT is turned off). Are you sure they have only 7 cores? 

Also, you can always run the experiment without the problematic node to test whether it is causing the problem.

**Comment by mustansarsaeed** [comment]
@yilongli I have run `user_loop` program on `rc05` it showed following output:

```
jitter 0: 357176 cycles, timestamp 25254076774421317, delta 25254076774421317
jitter 1: 350474 cycles, timestamp 25254077023822861, delta 249401544
jitter 2: 353049 cycles, timestamp 25254077273233697, delta 249410836
jitter 3: 354003 cycles, timestamp 25254077522642876, delta 249409179
jitter 4: 355327 cycles, timestamp 25254077772052452, delta 249409576
.. more items  trimmed  till jitter 999... 
jitter 99: 354418 cycles, timestamp 25254098722343445, delta 113015594
```
What this output corresponds to ? Secondly, it on some cores governor is not set to `performance`, can this be the issue. I think it should not have any big different.

**Comment by yilongli** [comment]
`user_loop.cc` is running a busy loop that takes CPU timestamp using `rdtsc` repeatedly. Every time it sees a gap larger than a certain threshold, it prints out the size of the gap, in rdtsc cycles.

Can you be more specific? How many of the cores whose governors are not correctly set? On one node? On all nodes?

**Comment by mustansarsaeed** [comment]
@yilongli  On one node, governor of 2 cores is not set. Rest of nodes are fine.

**Comment by yilongli** [comment]
@mustansarsaeed Ah, I just realized that the `homa-artifact-eval` tag og RAMCloud is not pointing to the correct [commit](https://github.com/PlatformLab/RAMCloud/commit/43198532f7b34a7e41291bfd3c061a8e5de4556f)! Can you switch to the master branch of RAMCloud and compile again? Sorry about that.

**Comment by mustansarsaeed** [comment]
Hi @yilongli Thank you for pointing to the correct commit. I have compiled and run the experiment again. I have found that while generating baseline numbers it only outputs `30` as hardcoded value for message bytes instead of actual bytes. please see basic baseline
[basic+dpdk_W4_baseline.txt](https://github.com/PlatformLab/homa-paper-artifact/files/3040788/basic%2Bdpdk_W4_baseline.txt) and homa baseline 
[homa+dpdk_W4_baseline.txt](https://github.com/PlatformLab/homa-paper-artifact/files/3040791/homa%2Bdpdk_W4_baseline.txt) . Can you please see if the commit is updated or anything missing. Thanks

**Comment by yilongli** [comment]
Oh shoot, I accidentally committed some junk code to the master branch. The problem is probably at this line: https://github.com/PlatformLab/RAMCloud/compare/373c5a9803e012ed8bf5aee217e43f6d4d55fe13...master#diff-ec3d8b3b1cd7aa99d0492be3169b2e26R3027. Can you change `30` to `size` and try again? If it works, I will fix it later.

**Comment by mustansarsaeed** [comment]
Above fix has worked successfully i.e. changing `30` to `size` .  Thanks

**Comment by mustansarsaeed** [comment]
Hi @yilongli , I have run experiment but it had created some weired results. I just created experiment data for `HomaP8`. Please check this file.
[slowdownImpl.txt](https://github.com/PlatformLab/homa-paper-artifact/files/3041806/slowdownImpl.txt). 
Absolute numbers
```
#   Size   Samples       Min       Avg       50%       90%       99%     99.9%       Max
#---------------------------------------------------------------------------------------
53      3084       5.3  22934733.2  2152503.8  71069602.2  306147181.3  342764616.7  346866815.5
... same continue ...
```
I think there is something wrong going. Please help me in this.

**Comment by mustansarsaeed** [comment]
@yilongli  baseline numbers are good i.e. 
[basic+dpdk_W4_baseline.txt](https://github.com/PlatformLab/homa-paper-artifact/files/3041823/basic%2Bdpdk_W4_baseline.txt) and 
[homa+dpdk_W4_baseline.txt](https://github.com/PlatformLab/homa-paper-artifact/files/3041824/homa%2Bdpdk_W4_baseline.txt)

**Comment by yilongli** [comment]
@mustansarsaeed Sorry, it can be very hard for me to help you debug this without access to the machines. Also, I am afraid I can't spend much time on this right now. Therefore, if you could pinpoint the problematic commit that results in the weird result, I could try to take a look at the code (there are only 7 additional commits as you can see in https://github.com/PlatformLab/RAMCloud/compare/373c5a9803e012ed8bf5aee217e43f6d4d55fe13...masterdiff-ec3d8b3b1cd7aa99d0492be3169b2e26R3027). Otherwise, I will have to try to fix this next time I get a cluster on cloudlab.

**Comment by mustansarsaeed** [comment]
@yilongli Thank you for the support. I am trying to debug the code. It looks `ClusterPerf` has some issues in calculating the numbers. Secondly, If you want I can provide you the access to the chassis I reserved, in case you want to quickly look at. Otherwise, I am trying.

**Comment by mustansarsaeed** [comment]
Hi @yilongli 
Sorry to bother you again. Experiment is terminated by displaying following logs:

```
1555006131.526953709 ClusterPerf.cc:1510 in echoMessageAsync ERROR[1]: Actual load factor 0.078, expecting 0.760, throttled 0.682
1555006132.566234860 DpdkDriver.cc:285 in ~DpdkDriver ERROR[1]: DpdkDriver deleted with 4002 packets still in use
```
Is this normal termination or something is missing? I ran experiment as `benchmarks/homa/scripts/run_workload.sh W4 16 600`

Regards

**Comment by yilongli** [comment]
No, this is a critical error. It's saying that the RAMCloud clients failed to generate 76% network load because the transport couldn't keep up with the load. The experiment is unstable in this case.

**Comment by mustansarsaeed** [comment]
Hi @yilongli , Thank you for the response. It is very difficult for me to debug why clients are not generating 76% load. Moreover, papers says 80% load, why we are not experimenting on 80% load? Can you please give me some pointer? I am on `master` branch. It may be the case that I get slow down numbers after successful completion of experiment as baseline numbers are perfect.

**Comment by yilongli** [comment]
76% load is measured at the application level while 80% load is the raw network load. The 4% difference is the Ethernet packet and HomaTransport protocol overhead.

I don't have a good idea on how to proceed at the moment. Have you figured out which commit causes the problem?

**Comment by mustansarsaeed** [comment]
I am trying to backtrace the commits. I have tried to compile the commit hash `952b503fbc1db4b3b178c8e30ae103d031590fa5` (which has commit log message: Included HomaTransport and benchmark code used in the SIGCOMM'18 paper.) but RAMCloud failed to compile, then I didn't spent time in debugging that compile issue. I started digging on `master` branch. I think it will be a 2 minute debugging for you if I provide cluster credentials. It may be months for me to dig the complete code. any pointers. branch `homa-artifact-eval` was good because experiment completed successfully but it generated little higher numbers.

**Comment by yilongli** [comment]
It's definitely not going to be 2 minutes' work. Unfortunately, I am busy working on a submission so I can't spend much time on it right now. I could probably try to take a closer look after the paper deadline on April 24th.

**Comment by mustansarsaeed** [comment]
Sure. You supported a lot. Thank you very much for that :) . Just one thing, should I continue `homa-artifact-eval` or `master` or backtrace commits for find a commit such that experiment completes successfully. thanks in advance

**Comment by yilongli** [comment]
I suggest that you look at the last 7 commits of the master branch and see if you can find the one that results in the weird numbers you mentioned earlier. That is, starting from this commit: https://github.com/PlatformLab/RAMCloud/commit/373c5a9803e012ed8bf5aee217e43f6d4d55fe13; this commit should be good except the slowdown numbers are a bit high.

**Comment by mustansarsaeed** [comment]
Ok. Thank you for the detailed guidance and best of luck for your paper :).

**Comment by mustansarsaeed** [comment]
Hi @yilongli , I checkout commit https://github.com/PlatformLab/RAMCloud/commit/6b1064d101742870c34d9cf36100027b559d5a85 . Experiment ran successfully, but numbers are high. attached is the generated plot 
[slowdownImpl_W4_rho76_tail.pdf](https://github.com/PlatformLab/homa-paper-artifact/files/3075898/slowdownImpl_W4_rho76_tail.pdf)

**Comment by mustansarsaeed** [comment]
Moreover, while compiling RAMCloud, i get warnings regarding system clock `make[2]: warning: Clock skew detected. Your build may be incomplete.`, does clock setting have any impact on RTTs calculations?

**Comment by yilongli** [comment]
No, clock skew between machines has nothing to do with RTT calculation. Message RTT is computed on the same machine.

**Comment by mustansarsaeed** [comment]
Hi @yilongli , I was just thinking are you sure that the experiment data on this repo is generated through code base at one of commits from https://github.com/PlatformLab/RAMCloud/commit/952b503fbc1db4b3b178c8e30ae103d031590fa5. Because I have tried multiple commits and the result is little bit high. Can you please confirm this? It may be the case that code base is not updated.

**Comment by yilongli** [comment]
I am pretty sure the code base is up to date. Perhaps the performance improvement is entirely from the latest commit.

**Comment by mustansarsaeed** [comment]
> It's definitely not going to be 2 minutes' work. Unfortunately, I am busy working on a submission so I can't spend much time on it right now. I could probably try to take a closer look after the paper deadline on April 24th.

I am waiting for your kind input as I have tried all commits, no improvement. Latest commit on master fails to produce the required load factor hence it terminates the experiment in abnormal fashion. and old commits produce high numbers. Please guide accordingly. I have a cluster, i can share with you or you may get the access to cluster. Your kind guidance will be appreciated.

**Comment by yilongli** [comment]
You can start by asking CloudLab staff how to give me access to the cluster. There isn't many m510 machines free at the moment so I can't get my own cluster. I will first take a look at the latest commit soon.

**Comment by mustansarsaeed** [comment]
Hi @yilongli ,

I have asked Cloudlab staff. They sent a following reply:

> Member need to signup (https://cloudlab.us/signup.php) and request to join the project that your experiment is a part of. 

experiment name : mustang7-QV48607

Can you please signup and initiate a request for joining the project. I'll approve the request.

**Comment by yilongli** [comment]
I need to know your project name (not your experiment name), which can be found under the membership tab.

**Comment by mustansarsaeed** [comment]
project name is `HomaResults`

**Comment by mustansarsaeed** [comment]
@yilongli I have given `root` privileges to you. Please check.

**Comment by mustansarsaeed** [comment]
Thank you @yilongli for the continuous support. The result has been produced with your fix.

**Comment by yilongli** [comment]
Great! Glad to know it works.
