### ISSUE TITLE
HomaTransport.cc:2134 in checkTimeouts error

### ISSUE THREAD

**Issue by mustansarsaeed** [PlatformLab/homa-paper-artifact#3]
Hi, I am running experiment on Cloud Utah cluster, I have executed command for 1 hour
`runworkload w3 16 3600`
 but get following echos. What is this referring to? Is this cluster related issue i.e. some node is not responding or some script limitation? I have tried multiple times. I have noticed if I run for shorter period then command executes successfully, If i run for longer time then it shows following error:

```
1553212514.498839795 HomaTransport.cc:2134 in checkTimeouts WARNING[1]: aborting ECHO RPC to server 14:58:d0:58:8f:c3, sequence 456095680: timeout
1553212514.498839795 HomaTransport.cc:2134 in checkTimeouts WARNING[1]: aborting ECHO RPC to server 14:58:d0:58:8f:c3, sequence 456095680: timeout
1553212514.498839795 HomaTransport.cc:2134 in checkTimeouts WARNING[1]: aborting ECHO RPC to server 14:58:d0:58:8f:c3, sequence 456095680: timeout
1553212514.498839795 HomaTransport.cc:2134 in checkTimeouts WARNING[1]: aborting ECHO RPC to server 14:58:d0:58:8f:c3, sequence 456095680: timeout
1553212514.498839795 HomaTransport.cc:2134 in checkTimeouts WARNING[1]: aborting ECHO RPC to server 14:58:d0:58:8f:c3, sequence 456095680: timeout
1553212514.498839795 HomaTransport.cc:2134 in checkTimeouts WARNING[1]: aborting ECHO RPC to server 14:58:d0:58:8f:c3, sequence 456095680: timeout
1553212514.498839795 HomaTransport.cc:2134 in checkTimeouts WARNING[1]: aborting ECHO RPC to server 14:58:d0:58:8f:c3, sequence 456095680: timeout
1553212514.498839795 HomaTransport.cc:2134 in checkTimeouts WARNING[1]: aborting ECHO RPC to server 14:58:d0:58:8f:c3, sequence 456095680: timeout
1553212514.498839795 HomaTransport.cc:2134 in checkTimeouts WARNING[1]: aborting ECHO RPC to server 14:58:d0:58:8f:c3, sequence 456095680: timeout
```

REgards,

**Comment by yilongli** [comment]
You can safely ignore these warnings. These warnings are simply saying that some RPCs are cancelled because they don't make progress in a certain time limit.

**Comment by mustansarsaeed** [comment]
This has generated `slowdownIml.txt` but has not completed the command. I am assuming this completes the command after generating file as I have gone through script. If these are the warnings,  should I abort this and execute next workload?

**Comment by yilongli** [comment]
No, you shouldn't abort the `run_workload.sh` script. These warnings are from the RAMCloud logs (you can find them under `RAMCloud/logs/latest`). They are printed after each run of the `scripts/clusterperf.py` command.

**Comment by mustansarsaeed** [comment]
Ok, Thank you for the support.
